---
abstract: 'YAML renderer for Mojo'
author:
  - 'Graham Barr <gbarr@cpan.org>'
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
module_name: MojoX::Renderer::YAML
name: MojoX-Renderer-YAML
no_index:
  directory:
    - inc
    - t
requires:
  YAML::Syck: 0
  perl: 5.8.8
resources:
  repository: http://git.goingon.net/?p=MojoX-Renderer-YAML.git
version: 0.10
